### PR TITLE
Add target

### PR DESCRIPTION
**Pull request by pedroassumpcao**
Adds the ability to define a target instead of using the default one. Useful for projects that are structured in a different way or use different view markup languages.

### CODE REVIEW

**Comment by danmayer** [comment]
This looks good and it makes sense why you would want to add support for different targets and directory structures. I am traveling back from Africa right now, so give me about two days to pull down run tests and review a bit closer. Or if one of my colleges gets to it first that is cool too.

**Comment by pedroassumpcao** [comment]
@danmayer that is nice. I will present your gem in a lightning talk at Raise.com (company I work for) on january 13th. It's seems very useful for us as we have a 3 year old code base, many engines etc.

**Comment by danmayer** [comment]
awesome this has been merged in and I bumped flatfoot to 0.0.5, and released to rubygems. Thanks for the improvements. Glad to see it has been helpful. Hope the talk goes well and others find it helpful as well. I gave a talk about a bunch of different tools we use to cleanup our old codebase, which you might find interesting. http://www.mayerdan.com/rubynation-production-code-analysis/ it covers flatfoot and some other tools as well.

**Comment by pedroassumpcao** [comment]
@danmayer nice! I also had seen your presentation last week, very nice tools. See ya!

**Pull request merged**
